const passport = require('passport')
const {Router} = require("express")
const controller = require('./controllers/taskController')

const router = Router()
router.use(passport.authenticate("jwt", {session: false}))

router.get("/getNew", controller.getNewTasks)
router.get("/getCheck", controller.getCheckTasks)
router.get("/getWorking", controller.getWorkingTasks)
router.get("/getReworking", controller.getReworkingTasks)
router.get("/getReady", controller.getReadyTasks)
router.get("/getOneTask/:id", controller.getOneTask)
router.post("/create", controller.createTask)
router.post("/change", controller.changeTaskStatus)
router.delete("/delete/:id", controller.deleteTask)
router.post("/commentary/create", controller.createCommentary)
router.post("/commentary/check", controller.commentaryCheck)
router.get("/getComment/:id", controller.getComment)
router.post("/taskCheck", controller.taskCheck)
module.exports = router